apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: virtink-cloud-controller-manager
build:
  local:
    useBuildkit: true
  artifacts:
    - image: virtink-cloud-controller-manager
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - config
