apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cloud-provider-virtink
build:
  artifacts:
    - image: virtink-ccm
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - deploy
