apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtink-cloud-controller-manager
  namespace: kube-system
  labels:
    app: virtink-cloud-controller-manager
spec:
  selector:
    matchLabels:
      app: virtink-cloud-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: virtink-cloud-controller-manager
    spec:
      serviceAccountName: virtink-cloud-controller-manager
      securityContext:
        runAsNonRoot: true
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: manager
          image: virtink-cloud-controller-manager:latest
          command:
            - /virtink-cloud-controller-manager
          args:
            - --cloud-provider=virtink
            - --cloud-config=/var/run/virtink-cloud-controller-manager/cloud-config
            # change to cluster-api-provider-virtink created Kubernetes cluster name
            - --cluster-name=virtink-cluster
          volumeMounts:
            - name: cloud-config
              mountPath: /var/run/virtink-cloud-controller-manager
              readOnly: true
            - name: cloud-kubeconfig
              mountPath: /var/run/cloud
              readOnly: true
      volumes:
        - configMap:
            name: cloud-config
            items:
              - key: cloud-config
                path: cloud-config
          name: cloud-config
        - secret:
            secretName: cloud-kubeconfig
            items:
              - key: kubeconfig
                path: kubeconfig
          name: cloud-kubeconfig
