apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtink-ccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtink-ccm
subjects:
  - kind: ServiceAccount
    name: virtink-ccm
    namespace: kube-system
